<?php $_helper = $this->helper('catalog/output'); ?>
<?php 
$_product = $this->getProduct();

$quickviewUrl = $_product->getProductQuickViewUrl();
if(Mage::app()->getFrontController()->getRequest()->isSecure())
    $quickviewUrl = str_replace('http://', 'https://', $url );

$categoryIds = $_product->getCategoryIds();
$category = null;
foreach($categoryIds as $categoryId) {
    $category = Mage::getModel('catalog/category')->load($categoryId);
}
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="links">
        <a id="saveSelection" style="color: #fff;background: #000;padding: 8px 22px; width:120px; float:left" href="#">ENREGISTRER LA SELECTION &gt;&gt;</a>
        <a style="color: #fff;background: #000;padding: 6px 16px; display:block;margin: 22px 0 0 36px;float: left;" href="#">f</a>

        <a style="color: #888;padding: 0; display:block;margin: 34px 0 0 36px;float: left;" class="ajaxQuickview" href="<?= $quickviewUrl?>">Voir les photos du produits >></a>
        <a style="color:#888;padding: 40px 0px;float:right" href="<?php echo $category->getUrl(); ?>">RETOUR <small>&gt;&gt;</small></a>
        <script type="text/javascript">
            jQuery( document ).ready(function($) {
                //jQuery.post("customercustomattributes/ajax/saveSelection", {someval: value}, function(data){...});
                $('#saveSelection').click( function() {
                    alert('selection :{ selectedTissuIndex : ' + selectedTissuIndex + ', selectedTissuBiMatiereIndex : ' + selectedTissuBiMatiereIndex + ', optionsBiMatiereActivatedIndices: ' + optionsBiMatiereActivatedIndices + '}');
                    var url = "<?= Mage::getBaseUrl()?>/ajax_product_customisation/ajax/save_selection";
                    jQuery.post(url, function( response ) {
                        var responseJson = $.parseJSON(response);
                        alert(responseJson.status + " : " + responseJson.msg);
                    });
                });
            });
        </script>
    </div>
    <div class="product-essential">
        
        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="product-shscriptop">
            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <div>
                <script type="text/javascript">
                    jQuery( document ).ready(function($) {
                        // hide left sidebar
                        jQuery(".header-sidebar").css('left', '-220px');
                        jQuery(".main-container").css('marginLeft', '0px');

                        // click event on tissuTypes
                        jQuery('.tissu-types .option').click(function(){
                            jQuery('.tissu-types .option').removeClass('selected');
                            jQuery( this ).addClass('selected');
                        });

                        $('.product-description').readmore({
                            collapsedHeight: 50,
                            speed: 75,
                            moreLink: '<a href="#">(Lire plus)</a>',
                            lessLink: '<a href="#">(Reduire)</a>'
                        });
                    });
                </script>

    			<div class="no-display">
    				<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
    				<input type="hidden" name="related_product" id="related-products-field" value="" />
    			</div>
                <div class="product-name">
                    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                    <?php //echo $this->getReviewsSummaryHtml($_product, false, true)?>
                    <?php if ($_product->isAvailable()): ?>
                    <p class="availability in-stock"><span><?php echo $this->__('In Stock') ?></span></p>
                    <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of Stock') ?></span></p>
                    <?php endif; ?>
                </div>
                
                <div class="product-description">
                    <?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'short_description') ?>
                </div>
                <center><hr style="width:40%; margin: 25px 0"/></center>

                <div class="tissu-types hidden">
                    <div class="option"><p>Popeline Coton</p></div>
                    <div class="option selected"><p>Velour</p></div>
                    <div class="option last"><p>Crêpe de soie</p></div>
                </div>

                <?php echo $this->getTierPriceHtml() ?>
                <?php //echo $this->getChildHtml('alert_urls') ?>            
                <?php if ($this->canEmailToFriend()): ?>
                    <!--<p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>-->
                <?php endif; ?>                        
                <!--<p class="product-sku"><?php echo $this->__('Product Code:') ?> <span><?php echo $_product->getSku() ?></span></p>-->
                
                <?php echo $this->getChildHtml('extrahint') ?>
                <?php echo $this->getChildHtml('other');?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif;?>
                <div id="switcherTissu_biMatiere" style="margin: 10px; display:none">
                    <h2>Bi-Matière</h2>
                </div>
                <div>
                        <div style="float:left;margin-top:10px; font-size:14px"> Modèle + options + livraison en france :  </div>
                        <div style="float:right"><?php echo $this->getChildHtml('product_type_data') ?></div>
                </div>
                <br/><br/>
                <div>
                    <a style="color:#888;float:right" href="<?php echo $category->getUrl(); ?>">Voir détail <small>&gt;&gt;</small></a>
                </div>

                <?php if (!$_product->isSaleable()): ?>
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php else://if (!$this->hasOptions()):?>
                    <div class="add-to-box">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php endif; ?>
            </div>
            </form>



            <!--<div class="product-collateral akordeon">
        <?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
                <div class="box-collateral <?php echo "box-{$alias}"?> akordeon-item">
                    <?php if ($title = $this->getChildData($alias, 'title')):?>
                    <div class="akordeon-item-head">
                        <div class="akordeon-item-head-container">
                            <div class="akordeon-heading">
                                <?php echo $this->escapeHtml($title); ?>
                            </div>
                        </div>
                    </div>
                    <?php endif;?>
                    <?php echo $html; ?>
                </div>
        <?php endforeach;?>
                <?php //echo $this->getChildHtml('reviews') ?>
                <?php //echo $this->getChildHtml('product_additional_data') ?>
                <?php //echo $this->getChildHtml('upsell_products') ?>                
            </div>-->
    </div>

        <div class="clearer"></div>
        <?php if(Mage::getStoreConfig('ajaxcart/addtocart/enableproduct')): ?>
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    if (!url) {
                        url = jQuery('#product_addtocart_form').attr('action');
                    }
                    url = url.replace("checkout/cart","ajaxcart/index"); // New Code
                    var data = jQuery('#product_addtocart_form').serialize();
                    data += '&isAjax=1';
                    jQuery('#loading-mask').show();
                    try {
                        jQuery.ajax({
                            url : url,
                            dataType : 'json',
                            type : 'post',
                            data : data,
                            success : function(data) {
                                jQuery('#loading-mask').hide();
                                if(data.status == 'ERROR'){
                                    alert(data.message);
                                }else{
                                    if(jQuery('.footer-menu .links')){
                                        jQuery('.footer-menu .links').replaceWith(data.toplink);
                                    }
                                    if(jQuery('.mini-cart-layer')){
                                        jQuery('.mini-cart-layer').replaceWith(data.minicart);
                                    }
                                    jQuery('#after-loading-success-message').show();
                                }
                            }
                        });
                    } catch (e) {
                    }                
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>
        <?php else : ?>
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
            
        //]]>
        </script>
        <?php endif;?>
        <script type="text/javascript">
        //<![CDATA[
            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>
    </div>
    <?php echo $this->getChildHtml('catalog.product.related') ?>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery('.akordeon.product-collateral').akordeon({ buttons: true, toggle: true });
        });
    </script>
</div>
