<div class="dashboard">
    <div class="page-title">
        <h1><?php echo $this->__('My Dashboard') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    <div class="block">
        <div class="block-title">
            <strong><span><?php echo $this->__('Account Information') ?></span></strong>
        </div>
        <div class="block-content">
            <?php echo $this->getChildHtml('customer.account.dashboard.extra') ?>
            <?php echo $this->getChildHtml('info') ?>
            <?php echo $this->getChildHtml('address') ?>
            <div class="box">
                <div class="box-title"><h3>Selections</h3></div>
                <div class="box-content">
                    <?php
                    $selections = json_decode($this->getCustomer()->getSelectionCustomizer(),true);
                    $selections = array_reverse($selections);
                    //echo $this->getCustomer()->getSelectionCustomizer();
                    $selectionId = count($selections) - 1;
                    foreach($selections as $row){
                        $selectionData = $row['selectionData'];
                        //var_dump($selectionData);
                        $date = strtotime( $row['date']);
                        $date = 'le ' . date('d-m-Y', $date). ' à ' . date('H:i',$date);
                        $nomSelection  = $selectionData['nomSelection'];
                        $productId  = $selectionData['productId'];
                        $product = Mage::getModel('catalog/product')->load($productId);
                        $selectionUrl = Mage::getBaseUrl().$product->getUrlPath().'?selectionId='.$selectionId;
                        echo '<a class="selectionText" style="color:#000;padding:4px 8px;font-size:15px;background-color:#F3F3F3;width:98%%;height: 25px;display: block;" href="'.$selectionUrl.'">'.$nomSelection .' <span style="font-size:10px;color:silver; float:right; margin-right:10px">' . $date .'</span></a><br/>';
                        $selectionId--;
                    }
                    //echo $this->getCustomer()->getSelectionCustomizer();
                    ?>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>
