<div class="dashboard">
    <div class="page-title">
        <h1><?php echo $this->__('My Dashboard') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('hello') ?>
    <?php echo $this->getChildHtml('top') ?>
    <div class="block">
        <div class="block-title">
            <strong><span><?php echo $this->__('Account Information') ?></span></strong>
        </div>
        <div class="block-content">
            <?php echo $this->getChildHtml('customer.account.dashboard.extra') ?>
            <?php echo $this->getChildHtml('info') ?>
            <?php echo $this->getChildHtml('address') ?>
            <div class="box">
                <div class="box-title"><h3>Selections</h3></div>
                <div class="box-content">
                    <?php
                    $selectionUrl = Mage::getBaseUrl() .'/ajax_product_customisation/ajax/load_selection';
                    $selections = json_decode( $this->getCustomer()->getSelectionCustomizer(),true);
                    //echo $this->getCustomer()->getSelectionCustomizer();
                    foreach($selections as $row){
                        $selectionData = $row['selectionData'];
                        $date = $row['date'];
                        //$jsonSelection = json_decode($selectionData, true);
                        $productId = $selectionData['productId'];
                        $product = Mage::getModel('catalog/product')->load($productId);
                        echo '<a href="'.$selectionUrl.'">'.$product->getName() .' / ' . $date .'</a>';
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>
