<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<?php if($_imgUrl): ?>
    <?php // echo $_imgHtml ?>
<?php endif; ?>
<?php 
    $_name=$this->getCurrentCategory()->getName();
    $_description=$this->getCurrentCategory()->getDescription();
?>
<div class="category-description-container">
    <div class="category-description-content">
    <h2 class="name"><?php echo $_helper->categoryAttribute($_category, $_name, 'name') ?></h2>
    <p><?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?></p>
</div>
</div>