<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<?php if($_imgUrl): ?>
    <?php // echo $_imgHtml ?>
<?php endif; ?>
<?php 
    $_name=$this->getCurrentCategory()->getName();
    $_description=$this->getCurrentCategory()->getDescription();
    $_urlVideo1 = $this->getCurrentCategory()->getVideo1Url();
    $_urlVideo2 = $this->getCurrentCategory()->getVideo2Url();
?>
<div class="category-description-container">
    <div id="toggleCategoryDescription" style="float: left;background-color: #000;width: 14px;height: 21px;margin-left: -14px;color: #fff;margin-top: 50px;padding: 0;">
        <a style="color:#fff;font-size: 9px;font-weight: bold;padding-left: 3px;" href="javascript::void"> &lt;</a>
    </div>

    <script type="text/javascript">
        jQuery( document ).ready(function() {
            jQuery('#toggleCategoryDescription').click(function(){
                var shown = (jQuery(".category-description-container").css('right') == '-228px' )? false: true;
                if(shown){
                    hideCategoryDescriptionBar();
                }else{
                    showCategoryDescriptionBar();
                }
            });

            function hideCategoryDescriptionBar(){
                jQuery(".category-description-container").animate({right: '-=228'}, { duration: 200, queue: false });
                jQuery(".category-products-container").animate({marginRight: '-=228'}, { duration: 200, queue: false });
            }

            function showCategoryDescriptionBar(){
                jQuery(".category-description-container").animate({right: '+=228'}, { duration: 200, queue: false });
                jQuery(".category-products-container").animate({marginRight: '+=228'}, { duration: 200, queue: false });
            }

        });
    </script>

    <div class="category-description-content">
    <h5 class="name"><?php echo $_helper->categoryAttribute($_category, $_name, 'name') ?></h2>
    <p style="text-align: justify; color:#2A2A2A"><?php echo $_helper->categoryAttribute($_category, $_description, 'description'); ?></p>
    <?php
        if( $_urlVideo1) {
            echo "<iframe width=\"100%\" height=\"100%\" src=\"//www.youtube.com/embed/$_urlVideo1\" frameborder=\"0\" allowfullscreen></iframe>";
        }

        if( $_urlVideo2) {
            echo "<iframe width=\"100%\" height=\"100%\" src=\"//www.youtube.com/embed/$_urlVideo2\" frameborder=\"0\" allowfullscreen></iframe>";
        }
    ?>

</div>
</div>