<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Acheter ce modèle'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <input type="hidden" name="choosed-options" id="choosed-options" />
        <input type="hidden" name="rendered-image" id="rendered-image" />

        <?php if(!$_product->isGrouped()): ?>
        <div class="qty-holder">
            <input type="hidden" name="qty" id="qty" maxlength="12" value="1" title="<?php echo $this->__('Qty') ?>"/>
        </div>
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery("#qty_inc").click(function(){
                jQuery("#qty").val((+jQuery("#qty").val() + 1) || 0);
            });
            jQuery("#qty_dec").click(function(){
                jQuery("#qty").val((jQuery("#qty").val() - 1 > 0)?(jQuery("#qty").val() - 1) : 0);
            });
        });
    </script>
<?php endif; ?>
