<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div class="messages_product_view">
    <center><h6>IMPORTANT</h6></center>
    <p>- Taille = 72 H
    Email : jusqu’à 72 h pour remplir les
    infos bulles.<br/>
    - Coupe environ 1 semaine
    email info quand le tissu est
    acheminé chez le confectionneur.<br/>
    - EXpedition environ 3 semaines
    Email info quand le coli  est
    expédié ( numéro de suivi )<br/>
    - Vous aurez 72 h pour renseigner vos mesure
        <p  style="text-align: right"><a href="#">Voir apreçu de la page</a></p>
    </p>
</div>
<div class="product-view">
    <div class="product-essential">

        <div class="product-img-box">
            <?php
                $_product = $this->getProduct();
                $_helper = $this->helper('catalog/output');
                $store = Mage::app()->getStore();
                $code  = $store->getCode();
            ?>
            <?php
                $ratio_width = Mage::getStoreConfig("trego_settings/product_view/ratio_width", $code);
                $ratio_height = Mage::getStoreConfig("trego_settings/product_view/ratio_height", $code);
                $ratio = $ratio_height / $ratio_width;
                $rnd_str = rtrim(base64_encode(md5(microtime())),"=");
            ?>
            <?php //var_dump($_product->getMediaGalleryImages());?>
            <?php if (count($_product->getMediaGalleryImages()) > 0): ?>
            <ul id="etalage">
            <?php foreach ($_product->getMediaGalleryImages()->getItemsByColumnValue('label', 'popup') as $_image): ?>
                                
                <?php
                    $image_src = Mage::getModel('catalog/product_media_config')->getMediaUrl($_image->getFile());
                    
                    $productThumbnail_src = Mage::getModel('catalog/product_media_config')->getMediaUrl($_product->getThumbnail());
                    
                    if($productThumbnail_src == $image_src) continue;

                ?>
                <li style="width:100%; height:70%">
                    <a class="fancy-images fancy-images_<?php echo $rnd_str; ?>" href="<?php echo $image_src; ?>"><span class="glyphicon glyphicon-search"></span></a>
                    
                    <div style="background: url('<?php echo $image_src; ?>'); background-size:cover; position: absolute; 
                    top:0px; opacity: 1; width: 100% !important;height: 40% !important;"><a style="position: absolute; color: #fff;background: #000;padding: 8px 22px; width:85px; bottom:10px; right:20px;" href="<?php echo $_product->getProductUrl(); ?>">ACHETER >></a></div>
                    <img class="etalage_source_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail', $_image->getFile())->resize(100, 100*$ratio)?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                </li>

            <?php endforeach; ?>
            </ul>            
            <?php endif; ?>
            <!--<div class="etalage-control">
                <a href="javascript:void(0)" class="etalage-prev">Previous</a>
                <a href="javascript:void(0)" class="etalage-next">Next</a>
            </div>-->
            <script type="text/javascript">
                jQuery(document).ready(function(){
                    reloadEtalage();
                    //jQuery(".product-img-box .etalage li.etalage_thumb").zoom();
                    setTimeout(function(){reloadEtalage();}, 500);
                    jQuery(window).resize(function(e){
                        reloadEtalage();
                    });
                    jQuery('.etalage-prev').on('click', function(){
                        etalage_previous();
                    });

                    jQuery('.etalage-next').on('click', function(){
                        etalage_next();
                    });
                    jQuery("a.fancy-images_<?php echo $rnd_str; ?>").fancybox();
                    function reloadEtalage(){
                        var width = jQuery('.product-view .product-img-box').width();
                        var src_img_width = 1000;
                        var src_img_height = 1000;
                        var ratio_width = <?php echo $ratio_width; ?>;
                        var ratio_height = <?php echo $ratio_height; ?>;
                        
                        src_img_width = 700 * ratio_width / ratio_height;
                        src_img_height = 700;
                        var height = width * ratio_height / ratio_width;
                        zoom_enabled = false;
                        jQuery('#etalage').etalage({
                            thumb_image_width: width,
                            thumb_image_height: height,
                            source_image_width: src_img_width,
                            source_image_height: src_img_height,
                            zoom_area_width: width,
                            zoom_area_height: height,
                            zoom_enable: zoom_enabled,
                            smallthumb_hide_single: false,
                            smallthumbs_position: 'bottom',
                            show_icon: false,
                            autoplay: false
                        });
                        jQuery('.product-view .product-img-box .etalage-control a').css('bottom',((jQuery('.etalage_small_thumbs').height()-25)/2)+"px");
                        jQuery('.etalage_small_thumbs').css('top', '30%');
                        jQuery('.etalage_thumb_image').css('width', 'auto');
                        jQuery('.etalage_thumb_image').css('height', 'auto');
                    }
                });
            </script>
            <div class="clear"></div>
        </div>

        <div class="clearer"></div>
        <?php if(Mage::getStoreConfig('ajaxcart/addtocart/enableproduct')): ?>
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    if (!url) {
                        url = jQuery('#product_addtocart_form').attr('action');
                    }
                    url = url.replace("checkout/cart","ajaxcart/index"); // New Code
                    var data = jQuery('#product_addtocart_form').serialize();
                    data += '&isAjax=1';
                    jQuery('#loading-mask').show();
                    try {
                        jQuery.ajax({
                            url : url,
                            dataType : 'json',
                            type : 'post',
                            data : data,
                            success : function(data) {
                                jQuery('#loading-mask').hide();
                                if(data.status == 'ERROR'){
                                    alert(data.message);
                                }else{
                                    if(jQuery('.footer-menu .links')){
                                        jQuery('.footer-menu .links').replaceWith(data.toplink);
                                    }
                                    if(jQuery('.mini-cart-layer')){
                                        jQuery('.mini-cart-layer').replaceWith(data.minicart);
                                    }
                                    jQuery('#after-loading-success-message').show();
                                }
                            }
                        });
                    } catch (e) {
                    }                
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>
        <?php else : ?>
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
            
        //]]>
        </script>
        <?php endif;?>
        <script type="text/javascript">
        //<![CDATA[
            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            //jQuery('.akordeon.product-collateral').akordeon({ buttons: true, toggle: true });
        });
    </script>
</div>
