<?php
//Get store id
$storeId    = Mage::app()->getStore()->getId();
$show_levels = 2;
//Get category model
$_category = Mage::getModel('catalog/category')->setStoreId($storeId);
$_cat = $_category->load(Mage::app()->getStore()->getRootCategoryId());

?>

<div class="nav-container">
    <a id="mobnav"><?php echo $this->__('Menu'); ?></a>
<?php
function hasMenuChildren($_cat){
    $storeId    = Mage::app()->getStore()->getId();
    $return_val = false;
    if($_cat->hasChildren()){
        $_children = $_cat->getChildren();
        $children_ids = explode(",", $_children);
        foreach ($children_ids as $child_id){
            $_child = Mage::getModel('catalog/category')->setStoreId($storeId)->load($child_id);
            if($_child->getIncludeInMenu()){
                $return_val = true;
            }
        }
    }
    return $return_val;
}
function cmpCatPosition($a, $b) {
    if ($a->position == $b->position)
        return 0;
    return ($a->position > $b->position) ? 1 : -1;
}
function showCategories($_category, $custom_html=''){
    $storeId = Mage::app()->getStore()->getId();
    $html = '';
    if($level < 3){
        if($level == 0){
            $html .= '<ul id="nav" class="menutype2">';
        } else {
            $html .= '<ul class="level'.$level.'">';
        }
        $_children = $_category->getChildren();
        $children_ids = explode(",", $_children);
        $categoryChildren = array();
        if ($children_ids) {
            foreach ($children_ids as $categoryId){
                $category = Mage::getModel('catalog/category')->load($categoryId);
                $categoryChildren[] = $category;
            }
        }

        usort($categoryChildren, 'cmpCatPosition');

        foreach ($categoryChildren as $_child){
            if($_child->getIncludeInMenu()){
                $html .= '<li class="level'.$level.'">';
                $url = $_child->getUrl();
                if(Mage::app()->getFrontController()->getRequest()->isSecure())
                    $url = str_replace('http://', 'https://', $url );
                $html .= '<a href ="'.$url.'"><span>';
                $html .= $_child->getName();
                $html .= '</span>';

                if( $level == 2 ){
                    if( $_child->getThumbnail() ){
                        $html .= '<img src="'.Mage::getBaseUrl('media').'catalog/category/'.$_child->getThumbnail().'"/>';
                    } else {
                        $html .= '<img src="'.Mage::getDesign()->getSkinUrl('images/np_cart_thumb.gif').'"/>';
                    }
                }
                $html .= '<em class="clear"></em></a>';
                /*if( hasMenuChildren($_child) && $level < $level_limit ){
                    if($level == 0 || $level == 1){
                        $html .= '<span class="plus"></span>';
                    }

                }*/
                $html .= showProducts($_child);
                $html .= '</li>';
            }
        }
        if($level == 0){
            $html .= $custom_html;
        }
        $html .= '</ul>';
    }
    return $html;
}

function showProducts($_category, $custom_html=''){
    $collection = $_category->getProductCollection()->addAttributeToSort('position');
    Mage::getModel('catalog/layer')->prepareProductCollection($collection);
    $html .= '<ul class="level productsBar">';
    foreach ($collection as $product) {
        //var_dump( $product );
        $html .= '<li class="level">';
        $url = $product->getProductQuickViewUrl();
        if(Mage::app()->getFrontController()->getRequest()->isSecure())
            $url = str_replace('http://', 'https://', $url );
        $html .= '<a class="ajaxQuickview" href ="'.$url.'"><div style="border:0;">';
        $html .= '<div class="product" style="width: 175px; height: 220px; margin:0;sbackground-position:center; background-size:cover; background-image:url(\''. Mage::helper('catalog/image')->init($product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(350) .'\')">';
        $html .= '<div class="overlay"><p style="position: absolute; left: 50%; margin-left: -62px; text-align: center; color: #fff;background: #000;padding: 8px 22px; width:80px; bottom:40px;">Voir &gt;&gt;</p></div>';
        $html .= '</div>';
        $html .= '<div style="padding:5px; width: 165px; margin-top: 4px;background-color: #fff;">';
        $html .= '<table><tr>';
        $html .= '<td style="max-width: 105px;"><div class="name">'. $product->getName() .'</div></td>';
        $html .= '<td style="vertical-align: middle;"><div style="text-align:right; width: 50px; vertical-align:middle;" class="price">'. showProductPrice($product) .'</div></td>';
        $html .= '</tr></table>';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '</li>';
    }
    $html .= '</ul>';

    return $html;
}

function showProductPrice($product){

  $html = Mage::helper('core')->currency($product->getFinalPrice(),true,false);


  return $html;
}

if (Mage::getStoreConfig("slidermenu/menu/show_custom_menu", $code) == 1) {
    $custom_html = Mage::getLayout()->createBlock('cms/block')->setBlockId(Mage::getStoreConfig("slidermenu/menu/custom_block_id", $code))->toHtml();
    if(substr($custom_html, 0,4)=="<ul>"){
        $custom_html = substr($custom_html, 4);
    }
    if(substr($custom_html, -5)=="</ul>"){
        $custom_html = substr($custom_html, 0, -5);
    }
}
echo showCategories($_cat, $custom_html);
?>
</div><?php //content ?>
<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery('.header-bground').append('<div class="tablet-overlay"></div>');
    jQuery("#nav li span.plus").click(function(event){
        event.stopPropagation();
        jQuery(".form-language .select-language .sbOptions").slideUp('fast');
        jQuery(".form-language .select-language .sbToggle").removeClass('sbToggleOpen');
        if(jQuery(this).hasClass('expanded')){
            jQuery(this).removeClass('expanded');
            jQuery(this).parent().removeClass('expanded');
            if(jQuery(this).parent().hasClass('level0'))
            {
                jQuery('.header-bground').removeClass('menu-expanded');
            }
            if(jQuery(window).width()>1024)
                jQuery(this).parent().children('ul').slideUp('fast');
            else if(jQuery(window).width()<768){
                jQuery(this).parent().children('ul').slideUp('fast');
            }
            else{
                jQuery(this).parent().children('ul').hide();
                jQuery('.tablet-overlay').hide();
            }
        } else {
            jQuery(this).parent().parent().children('li.expanded').children('ul').hide();
            jQuery(this).parent().parent().children('li.expanded').children('ul.expended').removeClass('expanded');
            jQuery(this).parent().parent().children('li.expanded').children('span.expanded').removeClass('expanded');
            jQuery(this).parent().parent().children('li').children('ul').children('li.expanded').children('ul').hide();
            jQuery(this).parent().parent().children('li').children('ul').children('li.expanded').children('span.expanded').removeClass('expanded');
            jQuery(this).parent().parent().children('li').children('ul').children('li.expanded').removeClass('expanded');
            jQuery(this).parent().parent().children('li.expanded').removeClass('expanded');
            jQuery('.tablet-overlay').hide();
            jQuery(this).addClass('expanded');
            jQuery(this).parent().addClass('expanded');
            if(jQuery(this).parent().hasClass('level0'))
            {
                jQuery('.header-bground').addClass('menu-expanded');
            }
            if(jQuery(window).width()>1024)
                jQuery(this).parent().children('ul').slideDown('fast');
            else if(jQuery(window).width()<768){
                jQuery(this).parent().children('ul').slideDown('fast');
            }
            else{
                jQuery(this).parent().children('ul').fadeIn();
                if(jQuery('li.level1.expanded').length > 0)
                {
                    var count = jQuery('li.level1.expanded').children('ul').children().length;
                    jQuery('.tablet-overlay').css('height', ((Math.ceil(count/2))*81+22)+'px');
                    jQuery('.tablet-overlay').fadeIn();
                }
            }
        }
    });

    //jQuery(".category-products").mCustomScrollbar();
    //jQuery(".productsBar").mCustomScrollbar({theme:"inset-3-dark"});
});
</script>