<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();

    $is_homepage = Mage::getBlockSingleton('page/html_header')->getIsHomePage();
    if($is_homepage) {
?>
    <div class="footer-container">
        <div class="footer">
            <div class="footer-menu">
                <?php echo $this->getChildHtml('footer_links') ?>
                <?php //echo $this->getChildHtml('footer_socialIcons'); ?>
                <?php echo $this->getChildHtml('footer_copyrights'); ?>
                <?php echo $this->getChildHtml('footer_leftNavBottom'); ?>
            </div>
        </div>
        <!--<a href="#" id="scroll-to-top">&nbsp</a>-->
        <script type="text/javascript">
            var windowScroll_t;
            jQuery(window).scroll(function () {

                clearTimeout(windowScroll_t);
                windowScroll_t = setTimeout(function () {

                    if (jQuery(this).scrollTop() > 100) {
                        jQuery('#scroll-to-top').fadeIn();
                    }
                    else {
                        jQuery('#scroll-to-top').fadeOut();
                    }

                }, 500);

            });

            jQuery('#scroll-to-top').click(function () {
                jQuery("html, body").animate({scrollTop: 0}, 600, "easeOutCubic");
                return false;
            });
        </script>
    </div>

<?php
    }
?>